// 与米歇尔换位模式使用的“可解布局模板”。
// 规则：目标角色保持自身块大小，仅切换到接近米歇尔区域的位置，
// 其余棋子自动采用该模板填充，确保整体布局可解。
export const SWAP_LAYOUTS = {
  zhangfei: {
    caocao: { x: 2, y: 0 },
    zhangfei: { x: 1, y: 0 },
    zhaoyun: { x: 3, y: 2 },
    machao: { x: 0, y: 0 },
    huangzhong: { x: 2, y: 2 },
    guanyu: { x: 0, y: 2 },
    soldier1: { x: 0, y: 3 },
    soldier2: { x: 3, y: 4 },
    soldier3: { x: 0, y: 4 },
    soldier4: { x: 1, y: 3 },
  },
  zhaoyun: {
    caocao: { x: 0, y: 0 },
    zhangfei: { x: 0, y: 2 },
    zhaoyun: { x: 2, y: 0 },
    machao: { x: 1, y: 2 },
    huangzhong: { x: 3, y: 0 },
    guanyu: { x: 2, y: 2 },
    soldier1: { x: 0, y: 4 },
    soldier2: { x: 3, y: 3 },
    soldier3: { x: 2, y: 3 },
    soldier4: { x: 3, y: 4 },
  },
  machao: {
    caocao: { x: 2, y: 0 },
    zhangfei: { x: 0, y: 0 },
    zhaoyun: { x: 3, y: 2 },
    machao: { x: 1, y: 0 },
    huangzhong: { x: 2, y: 2 },
    guanyu: { x: 0, y: 3 },
    soldier1: { x: 3, y: 4 },
    soldier2: { x: 1, y: 2 },
    soldier3: { x: 0, y: 4 },
    soldier4: { x: 0, y: 2 },
  },
  huangzhong: {
    caocao: { x: 0, y: 0 },
    zhangfei: { x: 0, y: 2 },
    zhaoyun: { x: 3, y: 0 },
    machao: { x: 1, y: 2 },
    huangzhong: { x: 2, y: 0 },
    guanyu: { x: 2, y: 3 },
    soldier1: { x: 2, y: 2 },
    soldier2: { x: 0, y: 4 },
    soldier3: { x: 3, y: 2 },
    soldier4: { x: 3, y: 4 },
  },
  guanyu: {
    caocao: { x: 1, y: 0 },
    zhangfei: { x: 0, y: 0 },
    zhaoyun: { x: 3, y: 0 },
    machao: { x: 0, y: 2 },
    huangzhong: { x: 3, y: 2 },
    guanyu: { x: 1, y: 2 },
    soldier1: { x: 1, y: 3 },
    soldier2: { x: 2, y: 3 },
    soldier3: { x: 0, y: 4 },
    soldier4: { x: 3, y: 4 },
  },
  soldier1: {
    caocao: { x: 2, y: 0 },
    zhangfei: { x: 0, y: 0 },
    zhaoyun: { x: 3, y: 3 },
    machao: { x: 0, y: 2 },
    huangzhong: { x: 1, y: 1 },
    guanyu: { x: 2, y: 2 },
    soldier1: { x: 1, y: 0 },
    soldier2: { x: 1, y: 3 },
    soldier3: { x: 0, y: 4 },
    soldier4: { x: 2, y: 3 },
  },
  soldier2: {
    caocao: { x: 0, y: 0 },
    zhangfei: { x: 0, y: 3 },
    zhaoyun: { x: 3, y: 0 },
    machao: { x: 2, y: 1 },
    huangzhong: { x: 3, y: 2 },
    guanyu: { x: 0, y: 2 },
    soldier1: { x: 2, y: 3 },
    soldier2: { x: 2, y: 0 },
    soldier3: { x: 3, y: 4 },
    soldier4: { x: 1, y: 3 },
  },
  soldier3: {
    caocao: { x: 2, y: 0 },
    zhangfei: { x: 0, y: 0 },
    zhaoyun: { x: 3, y: 3 },
    machao: { x: 0, y: 2 },
    huangzhong: { x: 1, y: 1 },
    guanyu: { x: 2, y: 2 },
    soldier1: { x: 0, y: 4 },
    soldier2: { x: 1, y: 3 },
    soldier3: { x: 1, y: 0 },
    soldier4: { x: 2, y: 3 },
  },
  soldier4: {
    caocao: { x: 0, y: 0 },
    zhangfei: { x: 0, y: 3 },
    zhaoyun: { x: 3, y: 0 },
    machao: { x: 2, y: 1 },
    huangzhong: { x: 3, y: 2 },
    guanyu: { x: 0, y: 2 },
    soldier1: { x: 1, y: 3 },
    soldier2: { x: 3, y: 4 },
    soldier3: { x: 2, y: 3 },
    soldier4: { x: 2, y: 0 },
  },
};
